import 'package:plantcare/domain/entities/catalog_plant.dart';
import 'package:plantcare/domain/entities/enums.dart';

/// Catálogo de plantas predefinidas para Firebase
class PlantCatalogData {
  /// Lista de plantas para agregar a Firestore
  static List<CatalogPlant> getDefaultPlants() {
    return [
      CatalogPlant(
        id: 'plant_001',
        name: 'Monstera deliciosa',
        scientificName: 'Monstera deliciosa',
        category: PlantCategory.indoor,
        description: 'Costilla de Adán - Planta tropical de interior muy popular en decoración moderna. Destaca por sus hojas grandes y perforadas.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 20,
        maxTemp: 30,
        humidityLevel: HumidityLevel.high,
        careTips: 'Riego: 1–2 veces por semana. Luz: abundante pero indirecta. Muy popular en decoración moderna.',
      ),
      CatalogPlant(
        id: 'plant_002',
        name: 'Pothos',
        scientificName: 'Epipremnum aureum',
        category: PlantCategory.indoor,
        description: 'Planta colgante muy fácil de cuidar, ideal para principiantes y espacios con luz indirecta.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 17,
        maxTemp: 30,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: cada 7–10 días. Luz: media o baja (muy adaptable). Excelente opción para iniciarse en el cuidado de plantas.',
      ),
      CatalogPlant(
        id: 'plant_003',
        name: 'Sansevieria',
        scientificName: 'Sansevieria trifasciata',
        category: PlantCategory.indoor,
        description: 'Lengua de suegra - Planta muy resistente, perfecta para quienes buscan un mantenimiento mínimo.',
        lightRequirement: LightRequirement.low,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 15,
        maxTemp: 30,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2–3 semanas. Luz: baja a alta (muy resistente). Ideal para espacios con poco cuidado diario.',
      ),
      CatalogPlant(
        id: 'plant_004',
        name: 'Ficus lyrata',
        scientificName: 'Ficus lyrata',
        category: PlantCategory.indoor,
        description: 'Higuera de hoja de violín - Muy decorativa y apreciada por sus hojas grandes y llamativas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 18,
        maxTemp: 25,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana. Luz: mucha luz natural. Necesita bastante luz para prosperar.',
      ),
      CatalogPlant(
        id: 'plant_005',
        name: 'Zamioculca',
        scientificName: 'Zamioculcas zamiifolia',
        category: PlantCategory.indoor,
        description: 'ZZ plant - Una de las plantas más resistentes para interiores.',
        lightRequirement: LightRequirement.low,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 18,
        maxTemp: 26,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2–3 semanas. Luz: baja o artificial. Muy buen desempeño con poco mantenimiento.',
      ),
      CatalogPlant(
        id: 'plant_006',
        name: 'Calathea',
        scientificName: 'Calathea spp.',
        category: PlantCategory.indoor,
        description: 'Planta tropical con hojas decorativas y patrones muy llamativos.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.high,
        minTemp: 18,
        maxTemp: 26,
        humidityLevel: HumidityLevel.high,
        careTips: 'Riego: 2–3 veces por semana (mantener húmeda). Luz: indirecta (nunca sol directo). Ideal para ambientes cálidos y húmedos.',
      ),
      CatalogPlant(
        id: 'plant_007',
        name: 'Areca',
        scientificName: 'Dypsis lutescens',
        category: PlantCategory.indoor,
        description: 'Palmera elegante que aporta textura y volumen a cualquier interior.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 18,
        maxTemp: 24,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1–2 veces por semana. Luz: abundante indirecta. Muy buena para espacios grandes.',
      ),
      CatalogPlant(
        id: 'plant_008',
        name: 'Dracaena marginata',
        scientificName: 'Dracaena marginata',
        category: PlantCategory.indoor,
        description: 'Planta decorativa con hojas largas y delgadas, muy típica en oficinas y salas.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 18,
        maxTemp: 26,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: cada 10–14 días. Luz: indirecta o semisombra. Muy cómoda para entornos urbanos.',
      ),
      CatalogPlant(
        id: 'plant_009',
        name: 'Ficus elastica',
        scientificName: 'Ficus elastica',
        category: PlantCategory.indoor,
        description: 'Árbol del caucho - Planta habitual en casas por su adaptabilidad y hojas brillantes.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 16,
        maxTemp: 24,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana. Luz: media (tolera poca luz). Muy habitual en hogares por su adaptabilidad.',
      ),
      CatalogPlant(
        id: 'plant_010',
        name: 'Helecho de Boston',
        scientificName: 'Nephrolepis exaltata',
        category: PlantCategory.indoor,
        description: 'Ideal para ambientes húmedos como baños y zonas con poca luz directa.',
        lightRequirement: LightRequirement.low,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.high,
        minTemp: 18,
        maxTemp: 24,
        humidityLevel: HumidityLevel.high,
        careTips: 'Riego: frecuente (tierra siempre húmeda). Luz: indirecta o baja. Ideal para ambientes húmedos.',
      ),
      CatalogPlant(
        id: 'plant_011',
        name: 'Aloe vera',
        scientificName: 'Aloe barbadensis miller',
        category: PlantCategory.succulent,
        description: 'Suculenta muy popular por su resistencia y su uso en macetas pequeñas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 18,
        maxTemp: 32,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2–3 semanas. Luz: mucho sol directo. Excelente para espacios soleados.',
      ),
      CatalogPlant(
        id: 'plant_012',
        name: 'Echeveria',
        scientificName: 'Echeveria elegans',
        category: PlantCategory.succulent,
        description: 'Suculenta compacta con rosetas suaves y apariencia ornamental.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 15,
        maxTemp: 30,
        humidityLevel: HumidityLevel.low,
        careTips: 'Necesita mucho sol y suelo muy drenante. Deja secar por completo entre riegos.',
      ),
      CatalogPlant(
        id: 'plant_013',
        name: 'Sedum',
        scientificName: 'Sedum spurium',
        category: PlantCategory.succulent,
        description: 'Planta suculenta de crecimiento bajo y resistente, ideal para macetas y jardineras.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 10,
        maxTemp: 30,
        humidityLevel: HumidityLevel.low,
        careTips: 'Tolera calor y sequía. Riega poco y deja el sustrato seco entre riegos.',
      ),
      CatalogPlant(
        id: 'plant_014',
        name: 'Haworthia',
        scientificName: 'Haworthia fasciata',
        category: PlantCategory.succulent,
        description: 'Suculenta pequeña con hojas marcadas, muy decorativa para interiores.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.monthly,
        wateringAmount: WateringAmount.low,
        minTemp: 16,
        maxTemp: 28,
        humidityLevel: HumidityLevel.low,
        careTips: 'Prefiere luz brillante pero indirecta. Mantén el sustrato casi seco.',
      ),
      CatalogPlant(
        id: 'plant_015',
        name: 'Kalanchoe',
        scientificName: 'Kalanchoe blossfeldiana',
        category: PlantCategory.succulent,
        description: 'Suculenta ornamental que produce inflorescencias brillantes y compactas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 18,
        maxTemp: 29,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego espaciado y luz fuerte. Excelente para macetas soleadas.',
      ),
      CatalogPlant(
        id: 'plant_016',
        name: 'Lavanda',
        scientificName: 'Lavandula angustifolia',
        category: PlantCategory.herb,
        description: 'Hierba aromática perfecta para balcones o macetas soleadas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.low,
        minTemp: 12,
        maxTemp: 28,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: 1 vez por semana, evitando el exceso de humedad. Luz: sol directo amplio. Ideal para exterior y terrazas.',
      ),
      CatalogPlant(
        id: 'plant_017',
        name: 'Albahaca',
        scientificName: 'Ocimum basilicum',
        category: PlantCategory.herb,
        description: 'Hierba culinaria fresca y aromática, ideal para macetas soleadas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 15,
        maxTemp: 30,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Necesita sol directo y riego constante para mantener hojas tiernas.',
      ),
      CatalogPlant(
        id: 'plant_018',
        name: 'Menta',
        scientificName: 'Mentha spp.',
        category: PlantCategory.herb,
        description: 'Hierba vigorosa que crece rápido y se adapta a macetas grandes.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.high,
        minTemp: 12,
        maxTemp: 26,
        humidityLevel: HumidityLevel.high,
        careTips: 'Mantén la tierra húmeda y poda con regularidad para controlar su crecimiento.',
      ),
      CatalogPlant(
        id: 'plant_019',
        name: 'Romero',
        scientificName: 'Salvia rosmarinus',
        category: PlantCategory.herb,
        description: 'Hierba perenne aromática, ideal para luz intensa y suelos secos.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 10,
        maxTemp: 28,
        humidityLevel: HumidityLevel.low,
        careTips: 'Prefiere suelo bien drenado y riego escaso. Tolera sequía moderada.',
      ),
      CatalogPlant(
        id: 'plant_020',
        name: 'Cilantro',
        scientificName: 'Coriandrum sativum',
        category: PlantCategory.herb,
        description: 'Hierba aromática de uso culinario, ideal para macetas de temporada.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 12,
        maxTemp: 28,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Prefiere riego regular y luz brillante. Se debe cosechar antes de florar.',
      ),
      CatalogPlant(
        id: 'plant_021',
        name: 'Rosa',
        scientificName: 'Rosa spp.',
        category: PlantCategory.flower,
        description: 'Flor ornamental clásica que requiere cuidados regulares para florecer bien.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 15,
        maxTemp: 30,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana. Luz: mucha luz directa. Necesita poda y buen drenaje.',
      ),
      CatalogPlant(
        id: 'plant_022',
        name: 'Gerbera',
        scientificName: 'Gerbera jamesonii',
        category: PlantCategory.flower,
        description: 'Flor colorida y vistosa, muy popular en macetas y jardines.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 16,
        maxTemp: 28,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Necesita luz intensa y riego moderado para sostener sus flores.',
      ),
      CatalogPlant(
        id: 'plant_023',
        name: 'Hibisco',
        scientificName: 'Hibiscus rosa-sinensis',
        category: PlantCategory.flower,
        description: 'Flor tropical de gran impacto visual y hojas brillantes.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.high,
        minTemp: 18,
        maxTemp: 32,
        humidityLevel: HumidityLevel.high,
        careTips: 'Le encanta el calor y la humedad. Riega con frecuencia y fertiliza en verano.',
      ),
      CatalogPlant(
        id: 'plant_024',
        name: 'Petunia',
        scientificName: 'Petunia hybrida',
        category: PlantCategory.flower,
        description: 'Flor de temporada muy usada en balcones y jardineras.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 12,
        maxTemp: 28,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Requiere sol pleno y riego regular para mantener la floración.',
      ),
      CatalogPlant(
        id: 'plant_025',
        name: 'Dalia',
        scientificName: 'Dahlia spp.',
        category: PlantCategory.flower,
        description: 'Flor tuberosa con flores grandes y variadas en color.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 14,
        maxTemp: 29,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Necesita mucho sol, suelo fértil y soporte para sus tallos.',
      ),
      CatalogPlant(
        id: 'plant_026',
        name: 'Olivo',
        scientificName: 'Olea europaea',
        category: PlantCategory.tree,
        description: 'Árbol mediterráneo ideal para exteriores y macetas grandes.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 10,
        maxTemp: 30,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2 semanas. Luz: sol directo. Prefiere suelos secos y bien drenados.',
      ),
      CatalogPlant(
        id: 'plant_027',
        name: 'Bonsái',
        scientificName: 'Bonsai spp.',
        category: PlantCategory.tree,
        description: 'Planta de estilo ornamental que requiere cuidados más precisos.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 15,
        maxTemp: 28,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana, ajustando según el sustrato. Luz: directa o muy abundante. Requiere poda y humedad moderada.',
      ),
      CatalogPlant(
        id: 'plant_028',
        name: 'Cítricos',
        scientificName: 'Citrus spp.',
        category: PlantCategory.tree,
        description: 'Árbol frutal de ambiente cálido con follaje brillante y frutos aromáticos.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 15,
        maxTemp: 32,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Requiere mucha luz y riego regular, además de fertilización periódica.',
      ),
      CatalogPlant(
        id: 'plant_029',
        name: 'Jacarandá',
        scientificName: 'Jacaranda mimosifolia',
        category: PlantCategory.tree,
        description: 'Árbol ornamental con floración morada y porte majestuoso.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 12,
        maxTemp: 30,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Necesita luz abundante y espacio para su desarrollo. Evita exceso de riego.',
      ),
      CatalogPlant(
        id: 'plant_030',
        name: 'Ficus benjamina',
        scientificName: 'Ficus benjamina',
        category: PlantCategory.tree,
        description: 'Árbol de interior con hojas pequeñas y crecimiento elegante.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 16,
        maxTemp: 28,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Necesita luz indirecta y riego moderado. Evita cambios bruscos de temperatura.',
      ),
      CatalogPlant(
        id: 'plant_031',
        name: 'Cactus barril',
        scientificName: 'Ferocactus spp.',
        category: PlantCategory.cactus,
        description: 'Cactus compacto con necesidades muy bajas de agua y buena tolerancia al calor.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.monthly,
        wateringAmount: WateringAmount.low,
        minTemp: 12,
        maxTemp: 35,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: una vez al mes. Luz: sol directo intenso. Mantener el sustrato seco entre riegos.',
      ),
      CatalogPlant(
        id: 'plant_032',
        name: 'Mammillaria',
        scientificName: 'Mammillaria spp.',
        category: PlantCategory.cactus,
        description: 'Cactus esférico con tubérculos visibles y flores pequeñas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.monthly,
        wateringAmount: WateringAmount.low,
        minTemp: 12,
        maxTemp: 35,
        humidityLevel: HumidityLevel.low,
        careTips: 'Necesita mucho sol y un sustrato muy seco. Evita agua en exceso.',
      ),
      CatalogPlant(
        id: 'plant_033',
        name: 'Opuntia',
        scientificName: 'Opuntia ficus-indica',
        category: PlantCategory.cactus,
        description: 'Cactus de hojas planas con espinas y aspecto robusto.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.monthly,
        wateringAmount: WateringAmount.low,
        minTemp: 10,
        maxTemp: 35,
        humidityLevel: HumidityLevel.low,
        careTips: 'Tolera calor y sequía. Usa maceta con drenaje libre.',
      ),
      CatalogPlant(
        id: 'plant_034',
        name: 'Gymnocalycium',
        scientificName: 'Gymnocalycium mihanovichii',
        category: PlantCategory.cactus,
        description: 'Cactus redondeado con espinas suaves y formas llamativas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.monthly,
        wateringAmount: WateringAmount.low,
        minTemp: 12,
        maxTemp: 30,
        humidityLevel: HumidityLevel.low,
        careTips: 'Prefiere sol intenso y riego muy espaciado. Ideal para macetas pequeñas.',
      ),
      CatalogPlant(
        id: 'plant_035',
        name: 'Acanthocereus',
        scientificName: 'Acanthocereus tetragonus',
        category: PlantCategory.cactus,
        description: 'Cactus columnar de crecimiento lento y aspecto exótico.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.monthly,
        wateringAmount: WateringAmount.low,
        minTemp: 13,
        maxTemp: 34,
        humidityLevel: HumidityLevel.low,
        careTips: 'Requiere horas de sol directo y un sustrato muy seco entre riegos.',
      ),
      CatalogPlant(
        id: 'plant_036',
        name: 'Jazmín',
        scientificName: 'Jasminum officinale',
        category: PlantCategory.outdoor,
        description: 'Enredadera perfumada que prospera al aire libre en zonas soleadas.',
        lightRequirement: LightRequirement.direct,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 12,
        maxTemp: 30,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Necesita soporte, riego regular y poda ligera para florecer bien.',
      ),
      CatalogPlant(
        id: 'plant_037',
        name: 'Geranio',
        scientificName: 'Pelargonium zonale',
        category: PlantCategory.outdoor,
        description: 'Planta ornamental de exterior con abundantes flores de temporada.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 10,
        maxTemp: 28,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Prefiere sol pleno y riego moderado. Retira flores marchitas para estimular rebrote.',
      ),
      CatalogPlant(
        id: 'plant_038',
        name: 'Tomillo',
        scientificName: 'Thymus vulgaris',
        category: PlantCategory.outdoor,
        description: 'Hierba aromática resistente para jardines secos y cestas colgantes.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 10,
        maxTemp: 28,
        humidityLevel: HumidityLevel.low,
        careTips: 'Tolera sequía y necesita suelo bien drenado. Poda para mantener forma compacta.',
      ),
      CatalogPlant(
        id: 'plant_039',
        name: 'Hiedra',
        scientificName: 'Hedera helix',
        category: PlantCategory.outdoor,
        description: 'Planta trepadora de exterior con crecimiento rápido y follaje denso.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 8,
        maxTemp: 26,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Aprecia sombra parcial y soporte. Mantén humedad moderada en verano.',
      ),
      CatalogPlant(
        id: 'plant_040',
        name: 'Buganvilla',
        scientificName: 'Bougainvillea spp.',
        category: PlantCategory.outdoor,
        description: 'Planta exótica de exterior con brácteas coloridas y porte arbustivo.',
        lightRequirement: LightRequirement.direct,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 14,
        maxTemp: 32,
        humidityLevel: HumidityLevel.low,
        careTips: 'Necesita sol directo y suelo seco para florecer con intensidad.',
      ),
    ];
  }
}