import 'package:plantcare/domain/entities/catalog_plant.dart';
import 'package:plantcare/domain/entities/enums.dart';

/// Catálogo de plantas predefinidas para Firebase
class PlantCatalogData {
  /// Lista de plantas para agregar a Firestore
  static List<CatalogPlant> getDefaultPlants() {
    return [
      CatalogPlant(
        id: 'plant_001',
        name: 'Monstera deliciosa',
        scientificName: 'Monstera deliciosa',
        category: PlantCategory.indoor,
        description: 'Costilla de Adán - Planta tropical de interior muy popular en decoración moderna. Destaca por sus hojas grandes y perforadas.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 20,
        maxTemp: 30,
        humidityLevel: HumidityLevel.high,
        careTips: 'Riego: 1–2 veces por semana. Luz: abundante pero indirecta. Muy popular en decoración moderna.',
      ),
      CatalogPlant(
        id: 'plant_002',
        name: 'Pothos',
        scientificName: 'Epipremnum aureum',
        category: PlantCategory.indoor,
        description: 'Planta colgante muy fácil de cuidar, ideal para principiantes y espacios con luz indirecta.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 17,
        maxTemp: 30,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: cada 7–10 días. Luz: media o baja (muy adaptable). Excelente opción para iniciarse en el cuidado de plantas.',
      ),
      CatalogPlant(
        id: 'plant_003',
        name: 'Sansevieria',
        scientificName: 'Sansevieria trifasciata',
        category: PlantCategory.indoor,
        description: 'Lengua de suegra - Planta muy resistente, perfecta para quienes buscan un mantenimiento mínimo.',
        lightRequirement: LightRequirement.low,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 15,
        maxTemp: 30,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2–3 semanas. Luz: baja a alta (muy resistente). Ideal para espacios con poco cuidado diario.',
      ),
      CatalogPlant(
        id: 'plant_004',
        name: 'Ficus lyrata',
        scientificName: 'Ficus lyrata',
        category: PlantCategory.indoor,
        description: 'Higuera de hoja de violín - Muy decorativa y apreciada por sus hojas grandes y llamativas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 18,
        maxTemp: 25,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana. Luz: mucha luz natural. Necesita bastante luz para prosperar.',
      ),
      CatalogPlant(
        id: 'plant_005',
        name: 'Zamioculca',
        scientificName: 'Zamioculcas zamiifolia',
        category: PlantCategory.indoor,
        description: 'ZZ plant - Una de las plantas más resistentes para interiores.',
        lightRequirement: LightRequirement.low,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 18,
        maxTemp: 26,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2–3 semanas. Luz: baja o artificial. Muy buen desempeño con poco mantenimiento.',
      ),
      CatalogPlant(
        id: 'plant_006',
        name: 'Calathea',
        scientificName: 'Calathea spp.',
        category: PlantCategory.indoor,
        description: 'Planta tropical con hojas decorativas y patrones muy llamativos.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.high,
        minTemp: 18,
        maxTemp: 26,
        humidityLevel: HumidityLevel.high,
        careTips: 'Riego: 2–3 veces por semana (mantener húmeda). Luz: indirecta (nunca sol directo). Ideal para ambientes cálidos y húmedos.',
      ),
      CatalogPlant(
        id: 'plant_007',
        name: 'Areca',
        scientificName: 'Dypsis lutescens',
        category: PlantCategory.indoor,
        description: 'Palmera elegante que aporta textura y volumen a cualquier interior.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 18,
        maxTemp: 24,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1–2 veces por semana. Luz: abundante indirecta. Muy buena para espacios grandes.',
      ),
      CatalogPlant(
        id: 'plant_008',
        name: 'Dracaena marginata',
        scientificName: 'Dracaena marginata',
        category: PlantCategory.indoor,
        description: 'Planta decorativa con hojas largas y delgadas, muy típica en oficinas y salas.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 18,
        maxTemp: 26,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: cada 10–14 días. Luz: indirecta o semisombra. Muy cómoda para entornos urbanos.',
      ),
      CatalogPlant(
        id: 'plant_009',
        name: 'Ficus elastica',
        scientificName: 'Ficus elastica',
        category: PlantCategory.indoor,
        description: 'Árbol del caucho - Planta habitual en casas por su adaptabilidad y hojas brillantes.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 16,
        maxTemp: 24,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana. Luz: media (tolera poca luz). Muy habitual en hogares por su adaptabilidad.',
      ),
      CatalogPlant(
        id: 'plant_010',
        name: 'Helecho de Boston',
        scientificName: 'Nephrolepis exaltata',
        category: PlantCategory.indoor,
        description: 'Ideal para ambientes húmedos como baños y zonas con poca luz directa.',
        lightRequirement: LightRequirement.low,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.high,
        minTemp: 18,
        maxTemp: 24,
        humidityLevel: HumidityLevel.high,
        careTips: 'Riego: frecuente (tierra siempre húmeda). Luz: indirecta o baja. Ideal para ambientes húmedos.',
      ),
      CatalogPlant(
        id: 'plant_011',
        name: 'Aloe vera',
        scientificName: 'Aloe barbadensis miller',
        category: PlantCategory.succulent,
        description: 'Suculenta muy popular por su resistencia y su uso en macetas pequeñas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 18,
        maxTemp: 32,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2–3 semanas. Luz: mucho sol directo. Excelente para espacios soleados.',
      ),
      CatalogPlant(
        id: 'plant_012',
        name: 'Lavanda',
        scientificName: 'Lavandula angustifolia',
        category: PlantCategory.herb,
        description: 'Hierba aromática perfecta para balcones o macetas soleadas.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.low,
        minTemp: 12,
        maxTemp: 28,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: 1 vez por semana, evitando el exceso de humedad. Luz: sol directo amplio. Ideal para exterior y terrazas.',
      ),
      CatalogPlant(
        id: 'plant_013',
        name: 'Rosa',
        scientificName: 'Rosa spp.',
        category: PlantCategory.flower,
        description: 'Flor ornamental clásica que requiere cuidados regulares para florecer bien.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 15,
        maxTemp: 30,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana. Luz: mucha luz directa. Necesita poda y buen drenaje.',
      ),
      CatalogPlant(
        id: 'plant_014',
        name: 'Olivo',
        scientificName: 'Olea europaea',
        category: PlantCategory.tree,
        description: 'Árbol mediterráneo ideal para exteriores y macetas grandes.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 10,
        maxTemp: 30,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2 semanas. Luz: sol directo. Prefiere suelos secos y bien drenados.',
      ),
      CatalogPlant(
        id: 'plant_015',
        name: 'Cactus barril',
        scientificName: 'Ferocactus spp.',
        category: PlantCategory.cactus,
        description: 'Cactus compacto con necesidades muy bajas de agua y buena tolerancia al calor.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.monthly,
        wateringAmount: WateringAmount.low,
        minTemp: 12,
        maxTemp: 35,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: una vez al mes. Luz: sol directo intenso. Mantener el sustrato seco entre riegos.',
      ),
      CatalogPlant(
        id: 'plant_016',
        name: 'Bonsái',
        scientificName: 'Bonsai spp.',
        category: PlantCategory.tree,
        description: 'Planta de estilo ornamental que requiere cuidados más precisos.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 15,
        maxTemp: 28,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana, ajustando según el sustrato. Luz: directa o muy abundante. Requiere poda y humedad moderada.',
      ),
    ];
  }
}