import 'package:plantcare/domain/entities/catalog_plant.dart';
import 'package:plantcare/domain/entities/enums.dart';

/// Catálogo de plantas predefinidas para Firebase
class PlantCatalogData {
  /// Lista de plantas para agregar a Firestore
  static List<CatalogPlant> getDefaultPlants() {
    return [
      CatalogPlant(
        id: 'plant_001',
        name: 'Monstera deliciosa',
        scientificName: 'Monstera deliciosa',
        category: PlantCategory.indoor,
        description: 'Costilla de Adán - Planta tropical de interior muy popular en decoración moderna. Known for its large, perforated leaves.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 20,
        maxTemp: 30,
        humidityLevel: HumidityLevel.high,
        careTips: 'Riego: 1–2 veces por semana. Luz: abundante pero indirecta. Muy popular en decoración moderna.',
      ),
      CatalogPlant(
        id: 'plant_002',
        name: 'Pothos',
        scientificName: 'Epipremnum aureum',
        category: PlantCategory.indoor,
        description: 'Planta colgante muy fácil de cuidar. Considerada de las más populares en España actualmente.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 17,
        maxTemp: 30,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: cada 7–10 días. Luz: media o baja (muy adaptable). Considerada de las más populares en España.',
      ),
      CatalogPlant(
        id: 'plant_003',
        name: 'Sansevieria',
        scientificName: 'Sansevieria trifasciata',
        category: PlantCategory.indoor,
        description: 'Lengua de suegra - Muy usada porque casi no necesita cuidados. Planta muy resistente.',
        lightRequirement: LightRequirement.low,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 15,
        maxTemp: 30,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2–3 semanas. Luz: baja a alta (muy resistente). Muy usada porque casi no necesita cuidados.',
      ),
      CatalogPlant(
        id: 'plant_004',
        name: 'Ficus lyrata',
        scientificName: 'Ficus lyrata',
        category: PlantCategory.indoor,
        description: 'Higuera de hoja de violín - Necesita bastante luz para prosperar. Muy decorativa.',
        lightRequirement: LightRequirement.high,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 18,
        maxTemp: 25,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana. Luz: mucha luz natural. Necesita bastante luz para prosperar.',
      ),
      CatalogPlant(
        id: 'plant_005',
        name: 'Zamioculca',
        scientificName: 'Zamioculcas zamiifolia',
        category: PlantCategory.indoor,
        description: 'ZZ plant - Muy común por su resistencia. Planta casi indestructible.',
        lightRequirement: LightRequirement.low,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.low,
        minTemp: 18,
        maxTemp: 26,
        humidityLevel: HumidityLevel.low,
        careTips: 'Riego: cada 2–3 semanas. Luz: baja o artificial. Muy común por su resistencia.',
      ),
      CatalogPlant(
        id: 'plant_006',
        name: 'Calathea',
        scientificName: 'Calathea spp.',
        category: PlantCategory.indoor,
        description: 'Planta tropical decorativa muy usada. Known for its beautiful patterned leaves.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.high,
        minTemp: 18,
        maxTemp: 26,
        humidityLevel: HumidityLevel.high,
        careTips: 'Riego: 2–3 veces por semana (mantener húmeda). Luz: indirecta (nunca sol directo). Planta tropical decorativa.',
      ),
      CatalogPlant(
        id: 'plant_007',
        name: 'Areca',
        scientificName: 'Dypsis lutescens',
        category: PlantCategory.indoor,
        description: 'Palmera - Muy usada para dar volumen en interiores. Aporta un toque tropical.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 18,
        maxTemp: 24,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1–2 veces por semana. Luz: abundante indirecta. Muy usada para dar volumen en interiores.',
      ),
      CatalogPlant(
        id: 'plant_008',
        name: 'Dracaena marginata',
        scientificName: 'Dracaena marginata',
        category: PlantCategory.indoor,
        description: 'Muy común en casas y oficinas. Planta decorativa con hojas largas y delgadas.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.biweekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 18,
        maxTemp: 26,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: cada 10–14 días. Luz: indirecta o semisombra. Muy común en casas y oficinas.',
      ),
      CatalogPlant(
        id: 'plant_009',
        name: 'Ficus elastica',
        scientificName: 'Ficus elastica',
        category: PlantCategory.indoor,
        description: 'Árbol del caucho - Muy habitual en hogares por su adaptabilidad. Tiene hojas grandes y brillantes.',
        lightRequirement: LightRequirement.medium,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.medium,
        minTemp: 16,
        maxTemp: 24,
        humidityLevel: HumidityLevel.medium,
        careTips: 'Riego: 1 vez por semana. Luz: media (tolera poca luz). Muy habitual en hogares por su adaptabilidad.',
      ),
      CatalogPlant(
        id: 'plant_010',
        name: 'Helecho de Boston',
        scientificName: 'Nephrolepis exaltata',
        category: PlantCategory.indoor,
        description: 'Ideal para ambientes húmedos como baños. Planta colgante con hojas plumosas.',
        lightRequirement: LightRequirement.low,
        wateringFrequency: WateringFrequency.weekly,
        wateringAmount: WateringAmount.high,
        minTemp: 18,
        maxTemp: 24,
        humidityLevel: HumidityLevel.high,
        careTips: 'Riego: frecuente (tierra siempre húmeda). Luz: indirecta o baja. Ideal para ambientes húmedos como baños.',
      ),
    ];
  }
}